version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cars_race
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network2

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DOCKER_ENV: "True"
      DATABASE_URL: postgres://user:password@db:5432/cars_race
    ports:
      - "8000:8000"
    networks:
      - app-network2

networks:
  app-network2:
    driver: bridge

volumes:
  postgres_data:
  